apiVersion: batch/v1
kind: CronJob
metadata:
  name: payroll-analyzer-cronjob
  namespace: finances
spec:
  schedule: "*/30 * * * *"  # Runs every minute
  concurrencyPolicy: Forbid  # Prevents concurrent runs
  startingDeadlineSeconds: 30  # Time within which the job should start
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: payroll-analyzer
              image: antoniobriperez/payroll-analyzer:v0.0.8  # Replace 'tagname' appropriately
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: finances-app-config
                - secretRef:
                    name: finances-app-secrets
              # If your application requires command overrides, specify them here
              # command: ["/bin/bash"]
              # args: ["-c", "while true; do sleep 30; done;"]
          restartPolicy: OnFailure  # Restart policy for failed jobs