apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: finances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      nodeSelector:
        "kubernetes.io/os": linux

      containers:
        - name: metabase-staging
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_DBNAME
              value: "metabase"
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              value: root
            - name: MB_DB_HOST
              value: '192.168.18.240'
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: finances-app-secrets
                  key: PG_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: finances
spec:
  type: LoadBalancer
  selector:
    app: metabase
  ports:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000