apiVersion: v1
kind: Secret
metadata:
  name: finances-app-secrets
  namespace: finances
stringData:
  PG_PASS: "${PG_PASS}"
  IMAP_PASS_ICLOUD: "${IMAP_PASS_ICLOUD}"
  IMAP_USER_ICLOUD: "${IMAP_USER_ICLOUD}"
