name: Build and Push Docker Image

# Trigger on push to main branch or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the Docker image'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for tag detection

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. Determine the Docker image tag
      - name: Determine Docker image tag
        id: tag
        run: |
          # Check if a manual tag was provided
          if [ "${{ github.event.inputs.tag }}" != "" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            # Check if the commit is tagged
            TAG_FROM_GIT=$(git tag --points-at HEAD)
            if [ -n "$TAG_FROM_GIT" ]; then
              TAG="$TAG_FROM_GIT"
            else
              # Default tag: YYYYMMDD-commitSHA
              DATE_TAG=$(date +%Y%m%d)
              COMMIT_SHA=${GITHUB_SHA::7}
              TAG="${DATE_TAG}-${COMMIT_SHA}"
            fi
          fi
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT

      # 5. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            antoniobriperez/payroll-analyzer:${{ steps.tag.outputs.TAG }}
            antoniobriperez/payroll-analyzer:latest

      # 6. Output the pushed image information
      - name: Image Info
        run: |
          echo "Docker image pushed: antoniobriperez/payroll-analyzer:${{ steps.tag.outputs.TAG }}"
          echo "Docker image tagged as latest: antoniobriperez/payroll-analyzer:latest"
