name: Obtener versión del runner

on:
    workflow_dispatch:

jobs:
    get-runner-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v2

            - name: Obtener versión del runner
              run: |
                python --version